# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab2.proto\"\x19\n\x07Request\x12\x0e\n\x06vector\x18\x01 \x01(\x05\";\n\x08Response\x12\x16\n\x0e\x62iggest_number\x18\x01 \x01(\x05\x12\x17\n\x0fsmallest_number\x18\x02 \x01(\x05\x32\x33\n\x0cOrder_Vector\x12#\n\x0cOrder_Vector\x12\x08.Request\x1a\t.Responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'lab2_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'lab2_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_ORDER_VECTOR = DESCRIPTOR.services_by_name['Order_Vector']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=14
  _REQUEST._serialized_end=39
  _RESPONSE._serialized_start=41
  _RESPONSE._serialized_end=100
  _ORDER_VECTOR._serialized_start=102
  _ORDER_VECTOR._serialized_end=153
# @@protoc_insertion_point(module_scope)
